//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonoteka2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NajdluzszeAlbumy
    {
        public string Tytuł { get; set; }
        public string Zespół { get; set; }
        public Nullable<int> Godziny { get; set; }
        public Nullable<int> Minuty { get; set; }
        public Nullable<int> Sekundy { get; set; }
    }
}
