//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonoteka2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wykonawca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wykonawca()
        {
            this.Umiejetnosc = new HashSet<Umiejetnosc>();
        }
    
        public int IdWykonawcy { get; set; }
        public int IdZespolu { get; set; }
        [Required(ErrorMessage = "Imiê nie mo¿e byæ puste!")]
        [RegularExpression(
            @"^([a-zA-Z])+$",
            ErrorMessage = "Imiê zawiera niedozwolone znaki!")]
        public string Imie { get; set; }
        [Required(ErrorMessage = "Imiê nie mo¿e byæ puste!")]
        [RegularExpression(
            @"^([a-zA-Z])+$",
            ErrorMessage = "Imiê zawiera niedozwolone znaki!")]
        public string Nazwisko { get; set; }
        public string Pseudonim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Umiejetnosc> Umiejetnosc { get; set; }
        public virtual Zespol Zespol { get; set; }
    }
}
